import type { Metadata } from 'next'


export const metadata: Metadata = {
	title: 'Serials',
	description: 'Generated by create next app',
}

export default function Serials() {
	return (
		<main>
			<div className='container'>
				<h1 className="text-4xl font-bold my-5">Serials</h1>
			</div>
		</main>
	)
}
